### ISSUE TITLE
strange release tag

### ISSUE THREAD

**Issue by mschiff** [Verezano/AISradar_pi#10]
Hi,

your tag for version 0.98 is named "aisradar_pi-0.98" where it should read v0.98 or something... could you please fix this as it would make packaging your plugin a lot easier, thank you!

**Comment by Verezano** [comment]
Hi,
Where are you packaging it into?I actually nee a v1.0 tag for the current release.
Regards Johan 


Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: mschiff <notifications@github.com> 
Datum: 31-12-16  13:57  (GMT+01:00) 
Aan: Verezano/radar_pi <radar_pi@noreply.github.com> 
Cc: Subscribed <subscribed@noreply.github.com> 
Onderwerp: [Verezano/radar_pi] strange release tag (#10) 

Hi,
your tag for version 0.98 is named "aisradar_pi-0.98" where it should read v0.98 or something... could you please fix this as it would make packaging your plugin a lot easier, thank you!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Verezano/radar_pi","title":"Verezano/radar_pi","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Verezano/radar_pi"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"strange release tag (#10)"}],"action":{"name":"View Issue","url":"https://github.com/Verezano/radar_pi/issues/10"}}}

**Comment by mschiff** [comment]
Hi,
I am packaging it for Gentoo Linux. If there is a release 1.0 there should be a new source code release as well. So yes, please!

Would be nice to have a sane source code release fo every software release here on github, thank you!
